# Generated by Django 4.1.7 on 2023-03-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(choices=[('Football', 'Football'), ('Cricket', 'Cricket'), ('Basketball', 'Basketball'), ('Volleyball', 'Volleyball'), ('Throwball', 'Throwball'), ('Badminton', 'Badminton'), ('TableTennis', 'TableTennis'), ('Tennis', 'Tennis'), ('NonMajor', 'NonMajor')], default='NonMajor', max_length=150)),
                ('team_size', models.IntegerField()),
                ('min_males', models.IntegerField()),
                ('min_females', models.IntegerField()),
            ],
        ),
    ]
