# Generated by Django 4.1.7 on 2023-03-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sports',
            name='category',
            field=models.CharField(choices=[('Football', 'Football'), ('Cricket', 'Cricket'), ('Basketball', 'Basketball'), ('Volleyball', 'Volleyball'), ('Throwball', 'Throwball'), ('Badminton', 'Badminton'), ('TableTennis', 'Table Tennis'), ('Tennis', 'Tennis'), ('NonMajor', 'Non Major Sport')], default='NonMajor', max_length=150),
        ),
    ]
