# Generated by Django 4.1.7 on 2023-03-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_alter_sports_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sports',
            old_name='team_size',
            new_name='max_team_size',
        ),
        migrations.AddField(
            model_name='sports',
            name='min_team_size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
