# Generated by Django 4.1.7 on 2023-03-08 17:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0004_alter_sportsmapping_player'),
        ('sports', '0003_rename_team_size_sports_max_team_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('round', models.CharField(choices=[('Round1', 'Round1'), ('Round2', 'Round2'), ('Round3', 'Round3'), ('Quaters', 'Quaters'), ('Semis', 'Semis'), ('Finals', 'Finals')], default='Round1', max_length=150)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures_as_sport', to='sports.sports')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures_as_team1', to='team.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures_as_team2', to='team.team')),
            ],
            options={
                'unique_together': {('round', 'team2'), ('round', 'team1')},
            },
        ),
    ]
