let icons = {
    "Badminton-MS": "/sportsicons/Badminton.png",
    "Badminton-MD": "/sportsicons/Badminton.png",
    "Badminton-WS": "/sportsicons/Badminton.png",
    "Badminton-WD": "/sportsicons/Badminton.png",
    "Badminton-MiD": "/sportsicons/Badminton.png",
    "TableTennis-MS": "/sportsicons/TableTennis.png",
    "TableTennis-MD": "/sportsicons/TableTennis.png",
    "TableTennis-WS": "/sportsicons/TableTennis.png",
    "TableTennis-WD": "/sportsicons/TableTennis.png",
    "TableTennis-MiD": "/sportsicons/TableTennis-MiD.png",
    "Throwball": "/sportsicons/TableTennis-MiD.png",
    "Football": "/sportsicons/Football.png",
    "Cricket": "/sportsicons/Cricket.png",
    "Volleyball": "/sportsicons/Volleyball.png",
    "Basketball": "/sportsicons/Basketball.png",
    "Basketball-W": "/sportsicons/Basketball.png",
    "Valorant": "/sportsicons/Valorant.png",
    "CodM": "/sportsicons/CodM.png",
    "Fifa-S": "/sportsicons/Fifa.png",
    "Fifa-D": "/sportsicons/Fifa.png",
    "GullyCricket": "/sportsicons/Cricket.png",
    "Foosball": "/sportsicons/Foosball.png",
    "Chess": "/sportsicons/Chess.png",
    "Gym": "/sportsicons/Gym.png",
    "Carroms": "/sportsicons/Carroms.png",
    "TugOfWar": "/sportsicons/TugOfWar.png",
}

export default icons;