const sd = () => {
    return [
        {
            "id": 1,
            "name": "Badminton - Men's Singles",
            "tag": "Badminton-MS",
            "type": "major",
            "icon": "/sportsicons/Badminton.png",
            "displayImage": "/sportsdisplay/Badminton-MS.gif",
            "rules": "/rules/Badminton.txt ",
            "rulesURL": "../../rulespdf/Badminton.pdf",
            "spoc": [{ "spoc_name": "Mallikarjun Chakoti", "spoc_contact": "74834 00351" }, { "spoc_name": "Vedant Mangrulkar ", "spoc_contact": "75880 69853" }, { "spoc_name": "Akhil", "spoc_contact": "76719 60642" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 0, "max_female": 0 }
        },
        {
            "id": 2,
            "name": "Badminton - Men's Doubles",
            "tag": "Badminton-MD",
            "type": "major",
            "icon": "/sportsicons/Badminton.png",
            "displayImage": "/sportsdisplay/Badminton-MD.gif",
            "rules": "/rules/Badminton.txt ",
            "rulesURL": "../../rulespdf/Badminton.pdf",
            "spoc": [{ "spoc_name": "Mallikarjun Chakoti", "spoc_contact": "74834 00351" }, { "spoc_name": "Vedant Mangrulkar ", "spoc_contact": "75880 69853" }, { "spoc_name": "Akhil", "spoc_contact": "76719 60642" }],
            "requirements": { "min_players": 2, "max_players": 2, "min_female": 0, "max_female": 0 }
        },
        {
            "id": 3,
            "name": "Badminton - Women's Singles",
            "tag": "Badminton-WS",
            "type": "major",
            "icon": "/sportsicons/Badminton.png",
            "displayImage": "/sportsdisplay/Badminton-WS.gif",
            "rules": "/rules/Badminton.txt ",
            "rulesURL": "../../rulespdf/Badminton.pdf",
            "spoc": [{ "spoc_name": "Mallikarjun Chakoti", "spoc_contact": "74834 00351" }, { "spoc_name": "Vedant Mangrulkar ", "spoc_contact": "75880 69853" }, { "spoc_name": "Akhil", "spoc_contact": "76719 60642" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 1, "max_female": 1 }
        },
        {
            "id": 4,
            "name": "Badminton - Women's Singles",
            "tag": "Badminton-WD",
            "type": "major",
            "icon": "/sportsicons/Badminton.png",
            "displayImage": "/sportsdisplay/Badminton-WD.gif",
            "rules": "/rules/Badminton.txt ",
            "rulesURL": "../../rulespdf/Badminton.pdf",
            "spoc": [{ "spoc_name": "Mallikarjun Chakoti", "spoc_contact": "74834 00351" }, { "spoc_name": "Vedant Mangrulkar ", "spoc_contact": "75880 69853" }, { "spoc_name": "Akhil", "spoc_contact": "76719 60642" }],
            "requirements": { "min_players": 2, "max_players": 2, "min_female": 2, "max_female": 2 }
        },
        {
            "id": 5,
            "name": "Badminton - Mixed Doubles",
            "tag": "Badminton-MiD",
            "type": "major",
            "icon": "/sportsicons/Badminton.png",
            "displayImage": "/sportsdisplay/Badminton-MiD.gif",
            "rules": "/rules/Badminton.txt ",
            "rulesURL": "../../rulespdf/Badminton.pdf",
            "spoc": [{ "spoc_name": "Mallikarjun Chakoti", "spoc_contact": "74834 00351" }, { "spoc_name": "Vedant Mangrulkar ", "spoc_contact": "75880 69853" }, { "spoc_name": "Akhil", "spoc_contact": "76719 60642" }],
            "requirements": { "min_players": 2, "max_players": 2, "min_female": 1, "max_female": 1 }
        },
        {
            "id": 6,
            "name": "Table Tennis - Men's Singles",
            "tag": "TableTennis-MS",
            "type": "major",
            "icon": "/sportsicons/TableTennis.png",
            "displayImage": "/sportsdisplay/TableTennis-MS.gif",
            "rules": "/rules/TableTennis-S.txt ",
            "rulesURL": "../../rulespdf/TableTennis.pdf",
            "spoc": [{ "spoc_name": "Bhavya Kapadia", "spoc_contact": "9082733928" }, { "spoc_name": "Kandarp Dave", "spoc_contact": "9023194943" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 0, "max_female": 0 }
        },
        {
            "id": 7,
            "name": "Table Tennis - Men's Doubles",
            "tag": "TableTennis-MD",
            "type": "major",
            "icon": "/sportsicons/TableTennis.png",
            "displayImage": "/sportsdisplay/TableTennis-MD.gif",
            "rules": "/rules/TableTennis-D.txt ",
            "rulesURL": "../../rulespdf/TableTennis.pdf",
            "spoc": [{ "spoc_name": "Bhavya Kapadia", "spoc_contact": "9082733928" }, { "spoc_name": "Kandarp Dave", "spoc_contact": "9023194943" }],
            "requirements": { "min_players": 2, "max_players": 2, "min_female": 0, "max_female": 0 }
        },
        {
            "id": 8,
            "name": "Table Tennis - Women's Singles",
            "tag": "TableTennis-WS",
            "type": "major",
            "icon": "/sportsicons/TableTennis.png",
            "displayImage": "/sportsdisplay/TableTennis-WS.gif",
            "rules": "/rules/TableTennis-S.txt ",
            "rulesURL": "../../rulespdf/TableTennis.pdf",
            "spoc": [{ "spoc_name": "Bhavya Kapadia", "spoc_contact": "9082733928" }, { "spoc_name": "Kandarp Dave", "spoc_contact": "9023194943" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 1, "max_female": 1 }
        },
        {
            "id": 9,
            "name": "Table Tennis - Women's Doubles",
            "tag": "TableTennis-WD",
            "type": "major",
            "icon": "/sportsicons/TableTennis.png",
            "displayImage": "/sportsdisplay/TableTennis-WD.jpeg",
            "rules": "/rules/TableTennis-D.txt ",
            "rulesURL": "../../rulespdf/TableTennis.pdf",
            "spoc": [{ "spoc_name": "Bhavya Kapadia", "spoc_contact": "9082733928" }, { "spoc_name": "Kandarp Dave", "spoc_contact": "9023194943" }],
            "requirements": { "min_players": 2, "max_players": 2, "min_female": 2, "max_female": 2 }
        },
        {
            "id": 10,
            "name": "Table Tennis - Mixed Doubles",
            "tag": "TableTennis-MiD",
            "type": "major",
            "icon": "/sportsicons/TableTennis.png",
            "displayImage": "/sportsdisplay/TableTennis-MiD.avif",
            "rules": "/rules/TableTennis-D.txt ",
            "rulesURL": "../../rulespdf/TableTennis.pdf",
            "spoc": [{ "spoc_name": "Bhavya Kapadia", "spoc_contact": "9082733928" }, { "spoc_name": "Kandarp Dave", "spoc_contact": "9023194943" }],
            "requirements": { "min_players": 2, "max_players": 2, "min_female": 1, "max_female": 1 }
        },
        {
            "id": 11,
            "name": "Throwball",
            "tag": "Throwball",
            "type": "major",
            "icon": "/sportsicons/Volleyball.png",
            "displayImage": "/sportsdisplay/Throwball.gif",
            "rules": "/rules/Throwball.txt ",
            "rulesURL": "../../rulespdf/Throwball(Mixed).pdf",
            "spoc": [{ "spoc_name": "Yukta ", "spoc_contact": "7022095151" }, { "spoc_name": "Ankrutee ", "spoc_contact": "9246809610" }],
            "requirements": { "min_players": 8, "max_players": 10, "min_female": 2, "max_female": 9 }
        },
        {
            "id": 12,
            "name": "Football",
            "tag": "Football",
            "type": "major",
            "icon": "/sportsicons/Football.png",
            "displayImage": "/sportsdisplay/Football.gif",
            "rules": "/rules/Football.txt ",
            "rulesURL": "../../rulespdf/Football.pdf",
            "spoc": [{ "spoc_name": "Rishit Mane", "spoc_contact": "77381 47865" }, { "spoc_name": "Sourav Dileep", "spoc_contact": "73563 11283" }, { "spoc_name": "Kushagra Singh", "spoc_contact": "96609 38712" }],
            "requirements": { "min_players": 6, "max_players": 9, "min_female": 0, "max_female": 9 }
        },
        {
            "id": 13,
            "name": "Cricket",
            "tag": "Cricket",
            "type": "major",
            "icon": "/sportsicons/Cricket.png",
            "displayImage": "/sportsdisplay/Cricket.gif",
            "rules": "/rules/Cricket.txt ",
            "rulesURL": "../../rulespdf/Cricket.pdf",
            "spoc": [{ "spoc_name": "Rithik Bansal", "spoc_contact": "9777297550" }, { "spoc_name": "Aditya Kaka", "spoc_contact": "9900149539" }, { "spoc_name": "Maheedhar", "spoc_contact": "9704525404" }],
            "requirements": { "min_players": 10, "max_players": 12, "min_female": 0, "max_female": 12 }
        },
        {
            "id": 14,
            "name": "Volleyball",
            "tag": "Volleyball",
            "type": "major",
            "icon": "/sportsicons/Volleyball.png",
            "displayImage": "/sportsdisplay/Volleyball.gif",
            "rules": "/rules/Volleyball.txt ",
            "rulesURL": "../../rulespdf/Volleyball.pdf",
            "spoc": [{ "spoc_name": "Jack", "spoc_contact": "7207537377" }, { "spoc_name": "Gouse Peer", "spoc_contact": "9346659784" }],
            "requirements": { "min_players": 7, "max_players": 9, "min_female": 0, "max_female": 9 }
        },
        {
            "id": 15,
            "name": "Basketball",
            "tag": "Basketball",
            "type": "major",
            "icon": "/sportsicons/Basketball.png",
            "displayImage": "/sportsdisplay/Basketball.gif",
            "rules": "/rules/Basketball.txt ",
            "rulesURL": "../../rulespdf/Basketball.pdf",
            "spoc": [{ "spoc_name": "Vishruth Vijay", "spoc_contact": "7022271553" }, { "spoc_name": "Siddeshwar", "spoc_contact": "8050597300" }],
            "requirements": { "min_players": 5, "max_players": 8, "min_female": 0, "max_female": 8 }
        },
        {
            "id": 16,
            "name": "Basketball Men 3v3",
            "tag": "Basketball-M3",
            "type": "major",
            "icon": "/sportsicons/Basketball.png",
            "displayImage": "/sportsdisplay/Basketball-M3.gif",
            "rules": "/rules/Basketball-3.txt ",
            "rulesURL": "../../rulespdf/Basketball.pdf",
            "spoc": [{ "spoc_name": "Vishruth Vijay", "spoc_contact": "7022271553" }, { "spoc_name": "Siddeshwar", "spoc_contact": "8050597300" }],
            "requirements": { "min_players": 3, "max_players": 4, "min_female": 0, "max_female": 0 }
        },
        {
            "id": 17,
            "name": "Basketball Women",
            "tag": "Basketball-W",
            "type": "major",
            "icon": "/sportsicons/Basketball.png",
            "displayImage": "/sportsdisplay/Basketball-W.gif",
            "rules": "/rules/Basketball-3.txt ",
            "rulesURL": "../../rulespdf/Basketball.pdf",
            "spoc": [{ "spoc_name": "Vishruth Vijay", "spoc_contact": "7022271553" }, { "spoc_name": "Siddeshwar", "spoc_contact": "8050597300" }],
            "requirements": { "min_players": 3, "max_players": 4, "min_female": 3, "max_female": 4 }
        },
        {
            "id": 18,
            "name": "Valorant",
            "tag": "Valorant",
            "type": "minor",
            "icon": "/sportsicons/Valorant.png",
            "displayImage": "/sportsdisplay/Valorant.gif",
            "rules": "/rules/Valorant.txt ",
            "rulesURL": "../../rulespdf/Valorant.pdf",
            "spoc": [{ "spoc_name": "Harshith", "spoc_contact": "91777 85261" }, { "spoc_name": "Aryan", "spoc_contact": "76709 92002" }],
            "requirements": { "min_players": 5, "max_players": 5, "min_female": 0, "max_female": 5 }
        },
        {
            "id": 19,
            "name": "CodM",
            "tag": "CodM",
            "type": "minor",
            "icon": "/sportsicons/CodM.png",
            "displayImage": "/sportsdisplay/CodM.gif",
            "rules": "/rules/CoDM.txt ",
            "rulesURL": "../../rulespdf/CoDM.pdf",
            "spoc": [{ "spoc_name": "Tanish", "spoc_contact": "79737 87028" },{ "spoc_name": "Aditya Priyadarshi", "spoc_contact": "77629 80068" }],
            "requirements": { "min_players": 5, "max_players": 5, "min_female": 0, "max_female": 5 }
        },
        {
            "id": 20,
            "name": "Fifa Singles",
            "tag": "Fifa-S",
            "type": "minor",
            "icon": "/sportsicons/Fifa.png",
            "displayImage": "/sportsdisplay/Fifa.gif",
            "rules": "/rules/Fifa.txt ",
            "rulesURL": "../../rulespdf/Fifa.pdf",
            "spoc": [{ "spoc_name": "Keshav Goyal", "spoc_contact": "89680 76237" }, { "spoc_name": "Aaditya Gole", "spoc_contact": "79725 13736" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 0, "max_female": 1 }
        },
        {
            "id": 21,
            "name": "Fifa Doubles",
            "tag": "Fifa-D",
            "type": "minor",
            "icon": "/sportsicons/Fifa.png",
            "displayImage": "/sportsdisplay/Fifa-D.gif",
            "rules": "/rules/Fifa.txt ",
            "rulesURL": "../../rulespdf/Fifa.pdf",
            "spoc": [{ "spoc_name": "Keshav Goyal", "spoc_contact": "89680 76237" }, { "spoc_name": "Aaditya Gole", "spoc_contact": "79725 13736" }],
            "requirements": { "min_players": 2, "max_players": 2, "min_female": 0, "max_female": 2 }
        },
        {
            "id": 22,
            "name": "Gully Cricket",
            "tag": "GullyCricket",
            "type": "minor",
            "icon": "/sportsicons/Cricket.png",
            "displayImage": "/sportsdisplay/GullyCricket.gif",
            "rules": "/rules/GullyCricket.txt ",
            "rulesURL": "../../rulespdf/GullyCricket.pdf",
            "spoc": [{ "spoc_name": "Allu Pavan Karthik Reddy", "spoc_contact": "7795933534" }, { "spoc_name": "Heet Vasani", "spoc_contact": "9409732131" }],
            "requirements": { "min_players": 5, "max_players": 6, "min_female": 1, "max_female": 6 }
        },
        {
            "id": 23,
            "name": "ClashRoyale",
            "tag": "ClashRoyale",
            "type": "minor",
            "icon": "/sportsicons/CR.jpg",
            "displayImage": "/sportsdisplay/CR.gif",
            "rules": "/rules/ClashRoyale.txt ",
            "rulesURL": "../../rulespdf/ClashRoyale.pdf",
            "spoc": [{ "spoc_name": "Narayana Udayagiri", "spoc_contact": "90329 5945" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 0, "max_female": 1 }
        },
        {
            "id": 24,
            "name": "Chess",
            "tag": "Chess",
            "type": "minor",
            "icon": "/sportsicons/Chess.png",
            "displayImage": "/sportsdisplay/Chess.gif",
            "rules": "/rules/Chess.txt ",
            "rulesURL": "../../rulespdf/Chess.pdf",
            "spoc": [{ "spoc_name": "Rishi", "spoc_contact": "7981569233" }, { "spoc_name": "Owais", "spoc_contact": "8296177123" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 0, "max_female": 1 }
        },
        {
            "id": 25,
            "name": "Powerlifting Men",
            "tag": "Powerlifting",
            "type": "minor",
            "icon": "/sportsicons/Gym.png",
            "displayImage": "/sportsdisplay/Gym.gif",
            "rules": "/rules/Spandan_Powerlifting.txt ",
            "rulesURL": "../../rulespdf/Spandan_powerlifting.pdf",
            "spoc": [{ "spoc_name": "Sparsh", "spoc_contact": "9479644539" },
            { "spoc_name": "Vidhu Arora", "spoc_contact": "9501969884" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 0, "max_female": 0 }
        },
        {
            "id": 26,
            "name": "Powerlifting Women",
            "tag": "Powerlifting-W",
            "type": "minor",
            "icon": "/sportsicons/Gym.png",
            "displayImage": "/sportsdisplay/Gym-W.gif",
            "rules": "/rules/Spandan_Powerlifting.txt ",
            "rulesURL": "../../rulespdf/Spandan_powerlifting.pdf",
            "spoc": [{ "spoc_name": "Sparsh", "spoc_contact": "9479644539" },
            { "spoc_name": "Vidhu Arora", "spoc_contact": "9501969884" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 1, "max_female": 1 }
        },
        {
            "id": 27,
            "name": "Carroms",
            "tag": "Carroms",
            "type": "minor",
            "icon": "/sportsicons/Carroms.png",
            "displayImage": "/sportsdisplay/Carroms.gif",
            "rules": "/rules/Carroms.txt ",
            "rulesURL": "../../rulespdf/Carroms.pdf",
            "spoc": [{ "spoc_name": "Keerthan", "spoc_contact": "6281845781" }, { "spoc_name": "Leela Vamsi", "spoc_contact": "93983 24355" }],
            "requirements": { "min_players": 2, "max_players": 2, "min_female": 0, "max_female": 2 }
        },
        {
            "id": 28,
            "name": "Tug Of War Men",
            "tag": "TugOfWar",
            "type": "minor",
            "icon": "/sportsicons/TugOfWar.png",
            "displayImage": "/sportsdisplay/TugOfWar.gif",
            "rules": "/rules/TugOfWar.txt ",
            "rulesURL": "../../rulespdf/TugOfWar.pdf",
            "spoc": [{ "spoc_name": "Sparsh", "spoc_contact": "9479644539" },
            { "spoc_name": "Vidhu Arora", "spoc_contact": "9501969884" }],
            "requirements": { "min_players": 5, "max_players": 7, "min_female": 0, "max_female": 0 }
        },
        {
            "id": 29,
            "name": "Tug Of War Women",
            "tag": "TugOfWar-W",
            "type": "minor",
            "icon": "/sportsicons/TugOfWar.png",
            "displayImage": "/sportsdisplay/TugOfWar-W.gif",
            "rules": "/rules/TugOfWar.txt ",
            "rulesURL": "../../rulespdf/TugOfWar.pdf",
            "spoc": [{ "spoc_name": "Sparsh", "spoc_contact": "9479644539" },
            { "spoc_name": "Vidhu Arora", "spoc_contact": "9501969884" }],
            "requirements": { "min_players": 5, "max_players": 7, "min_female": 5, "max_female": 7 }
        },
        {
            "id": 30,
            "name": "Tennis Singles",
            "tag": "Tennis-MS",
            "type": "major",
            "icon": "/sportsicons/Tennis.png",
            "displayImage": "/sportsdisplay/Tennis.gif",
            "rules": "/rules/Tennis.txt ",
            "rulesURL": "../../rulespdf/Tennis.pdf",
            "spoc": [{ "spoc_name": "Vikas K", "spoc_contact": "8762175731" }, { "spoc_name": "Kalyan ", "spoc_contact": "9701682407" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 0, "max_female": 1 }
        },
        {
            "id": 31,
            "name": "Tennis Doubles",
            "tag": "Tennis-MD",
            "type": "major",
            "icon": "/sportsicons/Tennis.png",
            "displayImage": "/sportsdisplay/Tennis-D.gif",
            "rules": "/rules/Tennis.txt ",
            "rulesURL": "../../rulespdf/Tennis.pdf",
            "spoc": [{ "spoc_name": "Vikas K", "spoc_contact": "8762175731" }, { "spoc_name": "Kalyan ", "spoc_contact": "9701682407" }],
            "requirements": { "min_players": 2, "max_players": 2, "min_female": 0, "max_female": 2 }
        },
        {
            "id": 32,
            "name": "BGMI",
            "tag": "BGMI",
            "type": "minor",
            "icon": "/sportsicons/BGMI.jpeg",
            "displayImage": "/sportsdisplay/bgmi.gif",
            "rules": "/rules/BGMI.txt ",
            "rulesURL": "../../rulespdf/BGMI.pdf",
            "spoc": [{ "spoc_name": "Rutul Patel ", "spoc_contact": "87589 87403" },{ "spoc_name": "Rishi Patel", "spoc_contact": "83206 00705" }],
            "requirements": { "min_players": 5, "max_players": 5, "min_female": 0, "max_female": 5 }
        },
        {
            "id": 33,
            "name": "Pentathlon Men",
            "tag": "Pentathlon",
            "type": "minor",
            "icon": "/sportsicons/Gym.png",
            "displayImage": "/sportsdisplay/Pentathlon.png",
            "rules": "/rules/Pentathlon.txt ",
            "rulesURL": "../../rulespdf/Pentathlon.pdf",
            "spoc": [{ "spoc_name": "Sparsh", "spoc_contact": "9479644539" },
            { "spoc_name": "Vidhu Arora", "spoc_contact": "9501969884" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 0, "max_female": 0 }
        },
        {
            "id": 34,
            "name": "Pentathlon Women",
            "tag": "Pentathlon-W",
            "type": "minor",
            "icon": "/sportsicons/Gym.png",
            "displayImage": "/sportsdisplay/Pentathlon.png",
            "rules": "/rules/Pentathlon.txt ",
            "rulesURL": "../../rulespdf/Pentathlon.pdf",
            "spoc": [{ "spoc_name": "Sparsh", "spoc_contact": "9479644539" },
            { "spoc_name": "Vidhu Arora", "spoc_contact": "9501969884" }],
            "requirements": { "min_players": 1, "max_players": 1, "min_female": 1, "max_female": 1 }
        },
    ]
}

export default sd;