# Generated by Django 4.1.7 on 2024-02-24 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0003_rename_team_size_sports_max_team_size_and_more'),
        ('team', '0005_team_phonenum_delete_sportsmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scoreboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_score', models.CharField(max_length=50)),
                ('round_num', models.IntegerField()),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoreboards', to='sports.sports')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_scores', to='team.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_scores', to='team.team')),
            ],
            options={
                'unique_together': {('team1', 'team2', 'sport', 'round_num')},
            },
        ),
    ]
