# Generated by Django 4.1.7 on 2023-03-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_newuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='rollNo',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
