# Generated by Django 4.1.7 on 2023-03-13 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_newuser_rollno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='rollNo',
            new_name='rollNum',
        ),
    ]
