# Generated by Django 4.1.7 on 2023-03-05 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_alter_sports_category'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'sport')},
        ),
    ]
