# Generated by Django 4.1.7 on 2023-03-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_sportsmapping_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='phoneNum',
            field=models.CharField(default='+919999999999', max_length=150),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SportsMapping',
        ),
    ]
